package com.moneygoat.app.data.entity
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * User represents a registered account holder in the MoneyGoat system.
 * 
 * This entity is used for:
 * 1. Local Authentication: Room verifies credentials during the login flow.
 * 2. Session Management: The 'id' and 'username' are used to filter all other 
 *    user-specific data (expenses, categories, goals).
 * 3. Cloud Identity: The 'username' serves as the unique path key in Firebase 
 *    Realtime Database.
 */
@Entity(tableName = "users")
data class User(
    /**
     * Unique identifier for each user. 
     * Auto-generated by SQLite to ensure no collisions.
     */
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    
    /**
     * Unique username chosen by the user during registration.
     */
    val username: String,
    
    /**
     * Password used for local authentication. 
     * In a production environment, this would be hashed for security.
     */
    val password: String
)
